/**
 * Coerce the two documented boolean tokens from a query string, and leave anything else untouched
 * so `@IsBoolean()` rejects it with a 422 — rather than silently treating garbage as `false`, which
 * is how a filter starts lying about what it filtered.
 *
 * This is the ONE home for **query-parameter** boolean parsing. Both admin list DTOs that need it
 * (`ProjectQueryDto`, `MessageListQueryDto`) import it from here.
 *
 * `src/config/env.validation.ts` declares a separate, similarly named helper. That is **deliberate,
 * not drift** (C-3): it `.trim().toLowerCase()`es first, so it also accepts `' TRUE '`. The two
 * inputs are not the same kind of thing — an environment variable is typed once by an operator into
 * a file or a secret store where trailing whitespace is invisible and a capitalized `TRUE` is a
 * reasonable spelling, whereas a query parameter is machine-generated by a client against a
 * published contract. Being lenient there would widen the API's accepted surface beyond what
 * `openapi.json` documents. **Do not "unify" the two** — they encode different tolerances on
 * purpose, and merging them would either loosen the API contract or break operator-typed config.
 */
export function toOptionalBoolean(value: unknown): unknown {
  if (value === 'true' || value === true) {
    return true;
  }
  if (value === 'false' || value === false) {
    return false;
  }
  return value;
}
